In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data=pd.read_csv('/content/drive/MyDrive/smart bridge/Assignment ML/3/audi.csv')

In [ ]:
data.head(5)

model  year  price transmission  mileage fuelType  tax   mpg  engineSize
0    A1  2017  12500       Manual    15735   Petrol  150  55.4         1.4
1    A6  2016  16500    Automatic    36203   Diesel   20  64.2         2.0
2    A1  2016  11000       Manual    29946   Petrol   30  55.4         1.4
3    A4  2017  16800    Automatic    25952   Diesel  145  67.3         2.0
4    A3  2019  17300       Manual     1998   Petrol  145  49.6         1.0

In [ ]:
data.isnull().any()

model           False
year            False
price           False
transmission    False
mileage         False
fuelType        False
tax             False
mpg             False
engineSize      False
dtype: bool

In [ ]:
data.isnull().sum()

model           0
year            0
price           0
transmission    0
mileage         0
fuelType        0
tax             0
mpg             0
engineSize      0
dtype: int64

In [ ]:
data['model'].unique()

array([' A1', ' A6', ' A4', ' A3', ' Q3', ' Q5', ' A5', ' S4', ' Q2',
       ' A7', ' TT', ' Q7', ' RS6', ' RS3', ' A8', ' Q8', ' RS4', ' RS5',
       ' R8', ' SQ5', ' S8', ' SQ7', ' S3', ' S5', ' A2', ' RS7'],
      dtype=object)

In [ ]:
data['transmission'].unique()

array(['Manual', 'Automatic', 'Semi-Auto'], dtype=object)

In [ ]:
data['fuelType'].unique()

array(['Petrol', 'Diesel', 'Hybrid'], dtype=object)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10668 entries, 0 to 10667
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   model         10668 non-null  object 
 1   year          10668 non-null  int64  
 2   price         10668 non-null  int64  
 3   transmission  10668 non-null  object 
 4   mileage       10668 non-null  int64  
 5   fuelType      10668 non-null  object 
 6   tax           10668 non-null  int64  
 7   mpg           10668 non-null  float64
 8   engineSize    10668 non-null  float64
dtypes: float64(2), int64(4), object(3)
memory usage: 750.2+ KB


In [ ]:
x1=data.iloc[:,0:2]
x2=data.iloc[:,3:9]
x=pd.concat([x1,x2],axis=1,join="outer")
y=data.iloc[:,2:3]
x=x.values
y=y.values



array([[' A1', 2017, 'Manual', ..., 150, 55.4, 1.4],
       [' A6', 2016, 'Automatic', ..., 20, 64.2, 2.0],
       [' A1', 2016, 'Manual', ..., 30, 55.4, 1.4],
       ...,
       [' A3', 2020, 'Manual', ..., 150, 49.6, 1.0],
       [' Q3', 2017, 'Automatic', ..., 150, 47.9, 1.4],
       [' Q3', 2016, 'Manual', ..., 150, 47.9, 1.4]], dtype=object)

In [ ]:
x


array([[' A1', 2017, 'Manual', ..., 150, 55.4, 1.4],
       [' A6', 2016, 'Automatic', ..., 20, 64.2, 2.0],
       [' A1', 2016, 'Manual', ..., 30, 55.4, 1.4],
       ...,
       [' A3', 2020, 'Manual', ..., 150, 49.6, 1.0],
       [' Q3', 2017, 'Automatic', ..., 150, 47.9, 1.4],
       [' Q3', 2016, 'Manual', ..., 150, 47.9, 1.4]], dtype=object)

In [ ]:
y

array([[12500],
       [16500],
       [11000],
       ...,
       [17199],
       [19499],
       [15999]])

In [ ]:
x.shape

(10668, 8)

In [ ]:
from sklearn.preprocessing  import StandardScaler,OneHotEncoder
from sklearn.compose import ColumnTransformer


ct=ColumnTransformer([("one",OneHotEncoder(),[0,1,2,4])],remainder="passthrough")
x=ct.fit_transform(x)


In [ ]:
x.shape

(10668, 57)

In [ ]:
scx= StandardScaler(with_mean=False)
x=scx.fit_transform(x)
x.toarray()


array([[3.01070328, 0.        , 0.        , ..., 2.2332347 , 4.27826497,
        2.32200038],
       [0.        , 0.        , 0.        , ..., 0.29776463, 4.95784496,
        3.3171434 ],
       [3.01070328, 0.        , 0.        , ..., 0.44664694, 4.27826497,
        2.32200038],
       ...,
       [0.        , 0.        , 2.59828044, ..., 2.2332347 , 3.83035997,
        1.6585717 ],
       [0.        , 0.        , 0.        , ..., 2.2332347 , 3.69907747,
        2.32200038],
       [0.        , 0.        , 0.        , ..., 2.2332347 , 3.69907747,
        2.32200038]])

In [ ]:
scy= StandardScaler(with_mean=False)
y=scy.fit_transform(y)
y

array([[1.06707252],
       [1.40853573],
       [0.93902382],
       ...,
       [1.46820643],
       [1.66454777],
       [1.36576747]])

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [ ]:
from sklearn.svm import SVR
svr=SVR()
svr.fit(x_train,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='scale',
    kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [ ]:
y_pred=svr.predict(x_test)

In [ ]:
y_pred

array([1.15153211, 2.08558035, 2.48382263, ..., 3.93578252, 2.61278792,
       0.85008836])

In [ ]:
from sklearn.metrics import r2_score
accuracy=r2_score(y_test,y_pred)

In [ ]:
accuracy

0.9479012276940633

In [ ]:
from sklearn.neighbors import KNeighborsRegressor
knn=KNeighborsRegressor(metric='euclidean',n_neighbors=3)
knn.fit(x_train,y_train)

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='euclidean',
                    metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                    weights='uniform')

In [ ]:
y_pred=knn.predict(x_test)

In [ ]:
from sklearn.metrics import r2_score
accuracy=r2_score(y_test,y_pred)


In [ ]:
accuracy

0.9489493760811063